my_list=[]
print(my_list)
my_list.extend([10,20,30,40])
print(my_list)
my_list.insert(1,15)
print(my_list)
my_list.extend([50, 60, 70])
print(my_list)
my_list.pop(-1)
print(my_list)
my_list.sort()
print(my_list)
my_list.index(30)
print(f"the index of 30 ={my_list.index(30)}")
